### ISSUE TITLE
Yarn tasks don't respect "keep_files" config setting.

### ISSUE THREAD

**Issue by kimisgold** [Foundation-for-Jekyll-sites/jekyll-foundation#70]
Running jekyll by itself will preserve files and directories in my `_sites` folder that I've identified in my `_config.yml` using `keep_files`. Running any of the yarn tasks will clean out my `_sites` directory and ignore `keep_files`.

**Comment by core77** [comment]
What happens if you create a folder (_myfiles) in the root directory of your project and add your folder [in the config include section](https://github.com/Foundation-for-Jekyll-sites/jekyll-foundation/blob/master/_config.yml#L11)?

**Comment by kimisgold** [comment]
@core77 It works, but doesn't quite fit my use case. I have a separate php project that needs to live within my jekyll directory, and I'd prefer jekyll not to touch it all. As I understand it, Jekyll's "keep_files" configuration is built for use cases like this, so all I want is for that setting to take effect.

**Comment by core77** [comment]
This project was built with the intention to fully replace the _site folder when 'yarn start' or 'yarn run build' scripts are running. That's why there's the clean gulp task which wipes the _site folder.

Jekyll is only needed here to generate the HTML. 

Perhaps you want to make your own fork to achieve what you want to do?
